"use client";

import React from "react";
import Link from "next/link";
import {
  ShieldCheck,
  Target,
  Sparkles,
  Scale,
  Users,
  CheckCircle2,
  ArrowRight,
  ChevronRight,
  BookOpen,
  Award,
  Lock,
  HeartHandshake,
} from "lucide-react";
import { PublicNavbar } from "@/components/PublicNavbar";
import { PublicFooter } from "@/components/PublicFooter";

export default function AboutPage() {
  const values = [
    {
      title: "Evidence Over Speculation",
      icon: ShieldCheck,
      description:
        "We believe no AI should generate advice without mathematical proof of evidence. If a claim cannot be verified against an approved institutional document, it is safely withheld.",
    },
    {
      title: "Radical Citation Transparency",
      icon: Target,
      description:
        "Every sentence generated by FINEE includes unambiguous page and paragraph citations, allowing human advisors and compliance officers to verify facts in one click.",
    },
    {
      title: "Fiduciary First Design",
      icon: Scale,
      description:
        "We build exclusively for regulated wealth managers, RIAs, and broker-dealers. Our features prioritize compliance soundness, supervisory controls, and audit readiness.",
    },
    {
      title: "Absolute Data Sovereignty",
      icon: Lock,
      description:
        "Your institutional compliance manuals, ADV filings, and client conversations are strictly confidential. We enforce a zero-model-training policy across all tiers.",
    },
  ];

  return (
    <div className="min-h-screen bg-[#06090e] text-gray-100 selection:bg-emerald-500/30 selection:text-emerald-200">
      <PublicNavbar />

      {/* Hero Section */}
      <section className="relative pt-32 pb-16 md:pt-40 md:pb-20 overflow-hidden">
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[400px] bg-emerald-500/10 rounded-full blur-[130px] pointer-events-none" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center space-y-6">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-950/60 border border-emerald-500/30 text-emerald-400 text-xs font-mono">
            <HeartHandshake className="w-3.5 h-3.5" />
            <span>Our Mission &amp; Purpose</span>
          </div>

          <h1 className="text-4xl sm:text-5xl font-extrabold text-white tracking-tight font-sans max-w-4xl mx-auto leading-tight">
            Pioneering verifiable intelligence for the{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 via-teal-300 to-emerald-200">
              financial advisory ecosystem.
            </span>
          </h1>

          <p className="text-sm sm:text-base text-gray-400 max-w-2xl mx-auto font-sans leading-relaxed">
            FINEE.ai was founded on a simple conviction: financial advisors need reliable, evidence-backed answers from their approved institutional manuals — not creative hallucinations.
          </p>
        </div>
      </section>

      {/* Mission & Vision Section */}
      <section className="py-16 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="p-8 rounded-2xl bg-surface border border-surface-border space-y-4 shadow-xl">
            <div className="w-12 h-12 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 flex items-center justify-center">
              <Target className="w-6 h-6" />
            </div>
            <h3 className="text-2xl font-bold text-white font-sans">Our Mission</h3>
            <p className="text-xs sm:text-sm text-gray-300 leading-relaxed font-sans">
              To empower wealth management professionals, compliance officers, and advisory desks with deterministic, zero-hallucination artificial intelligence that is strictly grounded in verified institutional truth.
            </p>
          </div>

          <div className="p-8 rounded-2xl bg-surface border border-surface-border space-y-4 shadow-xl">
            <div className="w-12 h-12 rounded-xl bg-blue-500/10 border border-blue-500/30 text-blue-400 flex items-center justify-center">
              <Sparkles className="w-6 h-6" />
            </div>
            <h3 className="text-2xl font-bold text-white font-sans">Our Vision</h3>
            <p className="text-xs sm:text-sm text-gray-300 leading-relaxed font-sans">
              A future where every advisory communication, fee calculation, and compliance determination is instantly auditable, transparently cited, and aligned with fiduciary integrity.
            </p>
          </div>
        </div>
      </section>

      {/* Core Values */}
      <section className="py-16 border-t border-surface-border bg-[#0a0f1d]/60">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
          <div className="text-center space-y-2">
            <h3 className="text-xs font-mono uppercase font-bold text-emerald-400">
              Guiding Principles
            </h3>
            <p className="text-2xl sm:text-3xl font-bold text-white font-sans">
              Our Core Fiduciary Commitments
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {values.map((v, i) => {
              const Icon = v.icon;
              return (
                <div
                  key={i}
                  className="p-6 rounded-2xl bg-surface border border-surface-border hover:border-surface-borderLight transition-all space-y-3 shadow-lg"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg bg-surface-raised border border-surface-border flex items-center justify-center text-emerald-400 shrink-0">
                      <Icon className="w-5 h-5" />
                    </div>
                    <h4 className="text-base font-bold text-white font-sans">{v.title}</h4>
                  </div>
                  <p className="text-xs sm:text-sm text-gray-300 leading-relaxed font-sans">
                    {v.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 border-t border-surface-border relative overflow-hidden text-center">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white font-sans">
            Experience the Future of Grounded Advisory
          </h2>
          <p className="text-sm sm:text-base text-gray-400 max-w-xl mx-auto">
            Join forward-thinking wealth managers and compliance officers who trust FINEE.ai.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3.5 pt-2">
            <Link
              href="/signup"
              className="w-full sm:w-auto px-7 py-3.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-sm flex items-center justify-center gap-2 transition-all shadow-lg hover:shadow-emerald-500/25 cursor-pointer"
            >
              <span>Get Started</span>
              <ChevronRight className="w-4 h-4" />
            </Link>
            <Link
              href="/contact"
              className="w-full sm:w-auto px-6 py-3.5 rounded-xl bg-surface-raised hover:bg-surface-elevated text-gray-200 hover:text-white border border-surface-border text-sm font-medium flex items-center justify-center gap-2 transition-all cursor-pointer"
            >
              <span>Contact Us</span>
              <ArrowRight className="w-4 h-4 text-gray-400" />
            </Link>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}
